name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: ${{ matrix.friendlyName }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        nodeVersion: [12, 14, 16, 18]
        arch: [x64]
        os: [macos-11, windows-2019, ubuntu-22.04]
        include:
          - os: macos-11
            friendlyName: macOS
          - os: windows-2019
            friendlyName: Windows
          - os: windows-2019
            friendlyName: Windows
            arch: x86
          - os: ubuntu-22.04
            friendlyName: Linux
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Node.js ${{ matrix.arch }}
        uses: niik/setup-node@f9547c97f4c519f71dc42e652d6d2c53f9527c1d
        with:
          node-version: 12
          node-arch: ${{ matrix.arch }}
      - name: Install and build dependencies
        run: yarn
        env:
          npm_config_arch: ${{ matrix.arch }}
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn is-it-pretty
      - name: Reset safe.directory
        run: git config --global --add safe.directory ""
        shell: bash
      - name: Test
        run: yarn test
        env:
          TEST: 1
