name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.friendlyName }} Node ${{matrix.nodeVersion}} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        nodeVersion: [18, 20]
        arch: [x64]
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: macos-latest
            friendlyName: macOS
          - os: windows-latest
            friendlyName: Windows
          - os: windows-2019
            friendlyName: Windows
            nodeVersion: 18
            arch: x86
            npm_config_arch: ia32
          - os: ubuntu-latest
            friendlyName: Linux
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Node.js ${{ matrix.nodeVersion }} (${{ matrix.arch }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodeVersion }}
          architecture: ${{ matrix.arch }}
      - name: Install and build dependencies
        run: yarn
        env:
          npm_config_arch: ${{ matrix.npm_config_arch }}
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn is-it-pretty
      - name: Reset safe.directory
        run: git config --global --add safe.directory ""
        shell: bash
      - name: Test
        run: yarn test
        env:
          TEST: 1
